### ISSUE TITLE
Баг с интерфейсом батарейных буферов.

### ISSUE THREAD

**Issue by Pilad** [IdealIndustrial/GT5Unofficial#142]
Не открываются интерфейсы battery bufferов на 16 слотов любого тира.

**Comment by Pilad** [comment]
Ломает https://github.com/IdealIndustrial/GT5Unofficial/commit/74dce1b156e8257aa5a1026daaa8e27b11d4c3db
В частности класс GT_Container_4by4.java.
Я думаю ,что все классы где используется GT_Container_4by4 перестали открываться.

**Comment by Pilad** [comment]
Дата ацесс хэтч, инпут и аутпут басы 16 и выше слотовые.

**Comment by AndreySolodovnikov** [comment]
fixed
