### ISSUE TITLE
[BUG]Adjustable Transformer ошибки в GUI

### ISSUE THREAD

**Issue by DNIWE041** [IdealIndustrial/GT5Unofficial#155]
**Описание**
Первые шесть слотов инвентаря персонажа (если начинать слева сверху) в GUI настраиваемого трансформатора представляют собой "кликабельные" ячейки (ЛКМ \ ПКМ), при нажатии на которые происходит только увеличение отдаваемых \ принимаемых ампер, выдаваемого напряжения.
Если в данные ячейки инвентаря заранее положить предметы, то баг всё равно воспроизводится, но с предметами взаимодействовать при открытом GUI трансформатора нельзя (ячейки работают как кнопки).

**Воспроизведение**
Поставить любой настраиваемый трансформатор. Открыть GUI, кликать по первым слотам инвентаря.

**Дополнительная информация**
[Скриншот](https://sun9-13.userapi.com/impg/Z_Q-jpDAZ9nGtu4tN9OPQrZ4GW73ZQTxvydNgA/T6RqWYw4qoA.jpg?size=359x334&quality=96&proxy=1&sign=b859590cb98ff0b28bf00daf1320f857&type=album)

**Среда**
Опишите среду в которой произошла ошибка
 - Как локалка, так и сервер (Ultramine).
 - Версия ИИС 1.17.0
 - Версия Java - 8u231

**Comment by AndreySolodovnikov** [comment]
done
