### ISSUE TITLE
[BUG] Исчез рецепт Wood Plank

### ISSUE THREAD

**Issue by Kabaganda** [IdealIndustrial/GT5Unofficial#158]
**Описание**
В версии сборки 1.17.0 исчез рецепт Wood Plank 4909:17809, предмет невозможно скрафтить. Проблема наблюдается и у остальных игроков. 

**Скриншоты**
![wood](https://user-images.githubusercontent.com/76907488/103479870-71b45480-4df2-11eb-8774-bfd9dc7a597b.png)
![Comp](https://user-images.githubusercontent.com/76907488/103479880-8395f780-4df2-11eb-9458-dc0fb106c488.png)

**Среда**
 - Клиент 1.17.0
 - Доп. моды: WorldEdit, LonelyBiome

**Comment by Pilad** [comment]
> 
> 
> **Описание**
> В версии сборки 1.17.0 исчез рецепт Wood Plank 4909:17809, предмет невозможно скрафтить. Проблема наблюдается и у остальных игроков.
> 
> **Скриншоты**
> ![wood](https://user-images.githubusercontent.com/76907488/103479870-71b45480-4df2-11eb-8774-bfd9dc7a597b.png)
> ![Comp](https://user-images.githubusercontent.com/76907488/103479880-8395f780-4df2-11eb-9458-dc0fb106c488.png)
> 
> **Среда**
> 
>     * Клиент 1.17.0
> 
>     * Доп. моды: WorldEdit, LonelyBiome

Быстрый фикс, открыть конфиг грега GregTech.cfg и задать в тру B:AddGTRecipesToIC2Machines=true

**Comment by AndreySolodovnikov** [comment]
уже скоро вернем все как было =)
