### ISSUE TITLE
[BUG] Ошибка плавки в Multi Smelter 

### ISSUE THREAD

**Issue by Kabaganda** [IdealIndustrial/GT5Unofficial#159]
**Описание**
В обновлении 1.17.0 сломался Multi Smelter 1084:1003, всегда перерабатывает продукт 1 к 1, даже если в рецепте написано иначе. Результат не зависит от количества предметов на входе, тира energy hatch, output hatch или нагревательных колец. Об этом баге сообщали и другие игроки. 

**Воспроизведение**
Кладём стак Crushed Copper Ore, на выходе должно быть 9 стаков Copper Nugget, выдаёт лишь 1 стак. 
![image](https://user-images.githubusercontent.com/76907488/103539884-9ffd6700-4eba-11eb-948c-120d9a540fb1.png)
![image](https://user-images.githubusercontent.com/76907488/103539903-a986cf00-4eba-11eb-9046-084d6397db81.png)

Кладём 32 Soldering Alloy Ingot, на выходе должно быть 4,5 стака Nugget, выдаёт лишь 32. 
![2021-01-04_18 29 31](https://user-images.githubusercontent.com/76907488/103540022-dcc95e00-4eba-11eb-95f0-ceccca9c88af.png)
![2021-01-04_18 29 42](https://user-images.githubusercontent.com/76907488/103540120-097d7580-4ebb-11eb-9222-5899580c6de4.png)
![2021-01-04_18 29 55](https://user-images.githubusercontent.com/76907488/103540128-0da99300-4ebb-11eb-929e-36f81a9dab49.png)

**Среда**
 - Клиент 1.17.0, конфиги не редактировал. 
 - Доп. моды: WorldEdit, LonelyBiome

**Comment by Pilad** [comment]
> 
> 
> **Описание**
> В обновлении 1.17.0 сломался Multi Smelter 1084:1003, всегда перерабатывает продукт 1 к 1, даже если в рецепте написано иначе. Результат не зависит от количества предметов на входе, тира energy hatch, output hatch или нагревательных колец. Об этом баге сообщали и другие игроки.
> 
> **Воспроизведение**
> Кладём стак Crushed Copper Ore, на выходе должно быть 9 стаков Copper Nugget, выдаёт лишь 1 стак.
> ![image](https://user-images.githubusercontent.com/76907488/103539884-9ffd6700-4eba-11eb-948c-120d9a540fb1.png)
> ![image](https://user-images.githubusercontent.com/76907488/103539903-a986cf00-4eba-11eb-9046-084d6397db81.png)
> 
> Кладём 32 Soldering Alloy Ingot, на выходе должно быть 4,5 стака Nugget, выдаёт лишь 32.
> ![2021-01-04_18 29 31](https://user-images.githubusercontent.com/76907488/103540022-dcc95e00-4eba-11eb-95f0-ceccca9c88af.png)
> ![2021-01-04_18 29 42](https://user-images.githubusercontent.com/76907488/103540120-097d7580-4ebb-11eb-9222-5899580c6de4.png)
> ![2021-01-04_18 29 55](https://user-images.githubusercontent.com/76907488/103540128-0da99300-4ebb-11eb-929e-36f81a9dab49.png)
> 
> **Среда**
> 
>     * Клиент 1.17.0, конфиги не редактировал.
> 
>     * Доп. моды: WorldEdit, LonelyBiome

Исправлено.
