### ISSUE TITLE
Изменились ID материалов, относящихся к моду EnderIO

### ISSUE THREAD

**Issue by GraySaw** [IdealIndustrial/GT5Unofficial#160]
**Описание**
В версии ИИС 1.17 изменились ID трёх материалов. Из-за этого поломались записанные шаблоны в МЕ-сети. Существующие до 1.17 предметы потерялись.

**Воспроизведение**
Обновиться с 1.16.1 до 1.17 при наличии в мире (например, в инвентаре) предметов из Soularium, RedstoneAlloy или ElectricalSteel.

**Ожидаемое поведение**
Предметы из указанных материалов должны сохраниться при обновлении на новую версию

**Дополнительная информация**
![image](https://user-images.githubusercontent.com/74758933/103635213-413afa80-4f59-11eb-9dde-3e5f408158cc.png)

на картинке ElectricalSteel Plate, которая прописана в файле MaterialFix.zs как
`<gregtech:gt.metaitem.01:17368>	Electrical Steel Plate`:
![image](https://user-images.githubusercontent.com/74758933/103635415-8a8b4a00-4f59-11eb-80fe-06383f51f7d2.png)

**Comment by Pilad** [comment]
Хорошо.Починим.
