### ISSUE TITLE
[BUG] Unable to stack crafted GT machines and placed in the world

### ISSUE THREAD

**Issue by uutest74** [IdealIndustrial/GT5Unofficial#164]
**Описание**
Механизмы Gregtech установленные в мире без каверов и т.п. и снятые ключем не идентичны  механизмам скрафченным. Из-за этого они не используются рецептами в МЕ, не стакаются и т.д.
Причиной, предположительно, является добавленный недавно water proof upgrade.

**Воспроизведение**
Крафтим 2 LV Machine hull, один устанавливаем в любом месте и забираем назад ключем, второй держим инвентаре.
После возвращения снятого hull в инвентаре они не объединяются в стак, стоят разными слотами.

**Ожидаемое поведение**
LV Machine hull после снятия из мира объединяется с скрафченым.

**Дополнительная информация**
от GraySaw
вот что пишет /mt hand для lv machine hull. Обы были выданы дизассемблером. Но один из них я установил в мир и потом мнял гаечным ключом
<gregtech:gt.blockmachines:11>.withTag({mWaterProof: 0 as byte})
<gregtech:gt.blockmachines:11>

**Среда**
И на сервере и в локальной игре баг проявляется.
ИИС 1.17 с патчем
java version "1.8.0_251"

**Comment by Pilad** [comment]
А если оба поставить в мир ? Состакаются?

**Comment by uutest74** [comment]
> 
> 
> А если оба поставить в мир ? Состакаются?

Да.

**Comment by Pilad** [comment]
Вот и считай , что по дефолту стоит кавер )

**Comment by AndreySolodovnikov** [comment]
исправил, спасибо за репорт, в обнове будет =)
