### ISSUE TITLE
[BUG] Fluid Filter & Processing Array

### ISSUE THREAD

**Issue by RayeS2070** [IdealIndustrial/GT5Unofficial#165]
**Описание**
Не стартует рецепт: жидкость из люка не забирается, электричество не расходуется. 

**Воспроизведение**
16 Fluid Filter в Processing Array.

**Среда**
 - Локальная сеть
 - Версия ИИС 1.17.0
 - Java 8 Update 241 (64-bit)

**Comment by Pilad** [comment]
Пофиксил для ПА и АПА.
