### ISSUE TITLE
[FR] Пофиксить зарядку CropAnalizer

### ISSUE THREAD

**Issue by theshock** [IdealIndustrial/GT5Unofficial#172]
CropAnalizer получается рано, на LV уровне. И как именно его заряжать, кроме как через батарейку - совершенно непонятно. Ни `ChargeBox (BatBad)` ни `LV Battery Buffer` его не заряжают.

Предлагаю или понизить требуемый уровень для зарядки до LV, чтобы механизмы соответсвующего тира его заряжали
Либо хотя бы описать через скрипты, что ему для зарядки нужен минимум MV тир.

**Comment by AndreySolodovnikov** [comment]
Сделано, анализер заряжается в лв мехах в том числе, в обнове будет
