### ISSUE TITLE
Исправить отсутствие дропа при взрыве машин.

### ISSUE THREAD

**Issue by Pilad** [IdealIndustrial/GT5Unofficial#208]
Нет дропа при взрыве машин , так как убрали нбт теги у машин после крафта.
ПРы которые добавляли дроп компонентов при взрыве:
https://github.com/IdealIndustrial/GT5Unofficial/commit/a006b76304b9d1a7ce34c2d7700aee6753f250f5#diff-9aa9c930d10dbcd402be3e0158d4b3fc6bfccec1ae84815e96d1217e8b241b2b
https://github.com/IdealIndustrial/GT5Unofficial/commit/a6301759b11c9b8b59f470f97ac5921490358bdd#diff-9aa9c930d10dbcd402be3e0158d4b3fc6bfccec1ae84815e96d1217e8b241b2b

**Comment by SapientMC** [comment]
А кому он нафиг нужен, если после взрыва обычно достают мир из бэкапа?

**Comment by Pilad** [comment]
> 
> 
> А кому он нафиг нужен, если после взрыва обычно достают мир из бэкапа?

если не нужен, то вырезать код ПРа вообще. Или починить. Незачем оставлять код ,который не пашет и может отработать фиг знает как.

**Comment by SapientMC** [comment]
Я за вырезать.

**Comment by shogun-kub** [comment]
Паша проявил недюжинную настойчивость и я исправил.

**Comment by Pilad** [comment]
ха-ха )) Там еще до кучи исправление дизассемблера )

**Comment by Pilad** [comment]
Одобрено. Закрываю.
