### ISSUE TITLE
[BUG] Iron nugget

### ISSUE THREAD

**Issue by randomnt** [IdealIndustrial/GT5Unofficial#217]
**Описание**
В неи есть два рецепта на пережигание Iron nugget в печи, первый в wrought iron, второй в steel. Иногда после перезапуска клиента они меняются местами, и на выходе из печи получается steel вместо wrought.

**Воспроизведение**
Оно когда как, просто перезапускать клиент.

**Дополнительная информация**
![ok](https://user-images.githubusercontent.com/24315457/142759654-fcf711b9-7f6f-4bf1-9abd-a2c49cf6e4c3.png)
![bug](https://user-images.githubusercontent.com/24315457/142759674-38443f30-4912-435e-9532-4bddfb7e2ab5.png)
И работают рецепты в верстаке ингот->нуггеты, нуггеты->ингот, если по квестам смотреть то они вроде отключены должны быть.
![изображение](https://user-images.githubusercontent.com/24315457/142759609-732e2a2c-fc41-4e93-862b-4c6e355bf81f.png)

**Среда**
Новая чистая ИИС 1.18.0
Java is version 1.8.0_311, using 64-bit architecture

**Comment by Pilad** [comment]
Сборка сломана. Скрипты отваливаются.

**Comment by Pilad** [comment]
Добавлены моды ,мало памяти или ещё что-то.

**Comment by randomnt** [comment]
Да, нашел, что-то ломается когда отключаю Underground Biomes
mods\undergroundBiomes-0.8-beta57-SC.jar
scripts\UB.zs

**Comment by randomnt** [comment]
Вобщем оставил мод включенным, задизаблил генерацию в конфиге config\UndergroundBiomes.cfg, так норм.

**Comment by Pilad** [comment]
Нельзя добавлять/удалять моды. Ломаешь сборку. Нужно честно писать,что делал. Сам поломал,а потом говоришь что всё плохо.
