### ISSUE TITLE
[FR]Отображение тира колец в НЕИ.

### ISSUE THREAD

**Issue by Pilad** [IdealIndustrial/GT5Unofficial#242]
Добавить отображение тира колец в неи
https://github.com/GTNewHorizons/GT5-Unofficial/commit/05b7da00508714f4b9f1622383e4b58b9c29ebab

**Comment by WiseProjects** [comment]
@Pilad  Я пробовал, но там не особо есть место куда вставлять, максимуум что получилось это в последнюю строку в конец, но целиком не влазит в окно, получаается кривовато. А по вертикали тоже строк не хватает - не влазит в окно

**Comment by WiseProjects** [comment]
![image](https://github.com/IdealIndustrial/GT5Unofficial/assets/58177535/823fce9b-6c84-48cb-bafe-4c24d46162fc)
можно вот так сделать, но хз норм или нет. Может просто Heat: написать тогда точно влезет

**Comment by SapientMC** [comment]
@Pilad Не влезает без перерисовки интерфейса. Не будем делать
