### ISSUE TITLE
[FR]Добавить галочки в NEI

### ISSUE THREAD

**Issue by Pilad** [IdealIndustrial/GT5Unofficial#254]
Добавляет на предметы галочки/красные крестики если в инвентаре есть или нет компонент крафта. Взято с JEI.
ПР с гтнх https://github.com/GTNewHorizons/NotEnoughItems/commit/e123ab2f30356697d9a49124b0973375ce4dea9a#
https://github.com/GTNewHorizons/NotEnoughItems/pull/130

**Comment by SapientMC** [comment]
Эти символы хороши только для верстака. А в мехах будут перекрывать количество.
