### ISSUE TITLE
[FR]Рецепт Conduit facade

### ISSUE THREAD

**Issue by DU-HAST** [IdealIndustrial/GT5Unofficial#262]
Нужно добавить рецепт крафта кондуит фасадов из жидкого греговского бетона отлитием напрямую в солидифаере. Избавит от лишней стадии крафта из байндеров и уберет ванильный рецепт эндерИО

**Comment by WiseProjects** [comment]
а можно поподробнее? какой тир? что в рецепте по входу и выходу? @DU-HAST @SapientMC

**Comment by DU-HAST** [comment]
> а можно поподробнее? какой тир? что в рецепте по входу и выходу? @DU-HAST @SapientMC

Да все просто. ЛВ тир солидифаер. а уж по количеству баланс искать нужно

**Comment by SapientMC** [comment]
@DU-HAST У нас уже есть рецепты в солидифаере, будут конфликтовать.
@WiseProjects Можно добавить рецепт в ассембрер: 8 Conduit Binder + Progr Circ Config 8 = Conduit Facade за 0,8 секунды при 8 eU/t.

**Comment by WiseProjects** [comment]
you can add the following line into the the script file **_scripts\EnderIO.zs_** 
`Assembler.addRecipe(<EnderIO:itemConduitFacade>, conduitBinder * 8, <gregtech:gt.integrated_circuit:8> * 0, 16, 8);`
