### ISSUE TITLE
[FR] Апнуть рецепт переработки ильменита

### ISSUE THREAD

**Issue by FireWarrior2** [IdealIndustrial/GT5Unofficial#263]
Сейчас рецепт переработки ильменита выглядит очень сомнительным, т.к. за 90 секунд получается 1 пыль рутила, который еще надо переработать. На начальных этапах на такую "роскошь" банально недостаточно энергии, а когда ее будет достаточно, с Марса пойдет чистый титан.

Предлагаю апнуть рецепт переработки в 9 раз: из 9 пылей ильменита и 9 углерода за 40 секунд получать 4 слитка сварочного железа и 4 пыли рутила.
Ну или снизить время рецепта до ~10 с, но вариант с объемом переработки выглядит более интересным.
![2023-05-09_11 29 54](https://user-images.githubusercontent.com/18097458/237051071-8e3e9818-18fa-49d4-b428-c1272bce1ab1.png)

**Comment by SapientMC** [comment]
Тут вся игра состоит из кучи переходов типа сначала "роскошь", потом "мусор".
