### ISSUE TITLE
[FR] Добавить в тултип микросхем их тир

### ISSUE THREAD

**Issue by FireWarrior2** [IdealIndustrial/GT5Unofficial#264]
**Относится ли ваша идея к ошибке(дизбалансу)?.**
Микросхемы нельзя найти в неи или мэ-сети по их тиру, что весьма неудобно.

**Опишите вашу идея**
Предлагаю добавить в тултип микросхемам их уровень, вместо текущих бесполезных тултипов.
Например, дописать в скрипте (для Microprocessor):
<name_circuit>.addTooltip(format.yellow("LV") + format.white(" Circuit level ") + format.yellow("1"));

**Приложения**
![2023-04-03_18 16 23](https://user-images.githubusercontent.com/18097458/237053195-cc5739d2-d953-441e-9e35-03280cd5cb9d.png)

**Comment by Pilad** [comment]
Может сделать как на гтнх? С новой строки, так оно нагляднее будет.
![316078612-0a9044af-7840-41f2-8ddb-a82c2b0b53e7](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/41838efd-459f-4137-a581-f49feb779f96)
Вот вроде ПР с гтнх https://github.com/GTNewHorizons/GT5-Unofficial/pull/1779

**Comment by WiseProjects** [comment]
простого способа сделать даже просто в 2 строки нет, в гтнх там целая либа для это сделана. Все примеры многострочных тултипов в ИИС сделаны либо через отдельный класс либо через Behavior. Отдельные классы под каждую микруху это точно бред, единственный разумный вариант - через behaviour, но имхо это говнокод(нецелевое использование класса). Если совсем честно, непонятно нафига оно вообще нужно, иконка же сразу показывает тир, можно даже тултип не читать
