### ISSUE TITLE
[BUG] Compressor не разбирается в Disassembler

### ISSUE THREAD

**Issue by FireWarrior2** [IdealIndustrial/GT5Unofficial#266]
**Описание**
Compressor не разбирается в Disassembler.

**Воспроизведение**
Посмотреть рецепты переработки любого Compressor.

**Ожидаемое поведение**
Должны быть рецепты переработки Compressor в Disassembler.

**Дополнительная информация**
![2023-05-23_20 20 39](https://github.com/IdealIndustrial/GT5Unofficial/assets/18097458/18b533cd-4d06-4bb2-ab70-acfadf2f9779)

**Среда**
Сингл, ИИС 1.18.0, Java 8.0.3110.11

**Comment by WiseProjects** [comment]
либо исправлено либо ты перепутал машины, на скриншоте у тебя явно не дизассемблер

**Comment by FireWarrior2** [comment]
На скриншоте, естественно, не дизассемблер, потому что рецепта переработки компрессора в нем попросту нет.
Положил сейчас компрессор в него, ничего не разбирается:
![2024-03-26_01 20 24](https://github.com/IdealIndustrial/GT5Unofficial/assets/18097458/a12173b8-fa8e-4158-920c-be4576436bd8)
