### ISSUE TITLE
[FR]Изменить функцию настраиваемого трансформатора.

### ISSUE THREAD

**Issue by Pilad** [IdealIndustrial/GT5Unofficial#269]
Трансформатор изначально был разработан как понижающий, что-бы убрать несколько трансформаторов в цепочке понижения напряжения. И нет смысла в текущей возможности повышать напряжение. Оно фактически работает так же как и режим понижение.
Предлагаю убрать возможность переключать его в повышение.

**Comment by SapientMC** [comment]
Повышающий режим нужен для сбора кучи ампер в 1
