### ISSUE TITLE
[FR] Уменьшить количество дизеля в рецепте Cetane-Boosted Diesel

### ISSUE THREAD

**Issue by FireWarrior2** [IdealIndustrial/GT5Unofficial#270]
**Относится ли ваша идея к ошибке(дизбалансу)?**
Идея относится к дизбалансу.

**Опишите вашу идею**
Предлагаю уменьшить количество дизеля (Fuel) в рецепте Cetane-Boosted Diesel до 4 ведер.

**Приложения**
Имеются рецепты, где 4 ведра Cetane-Boosted Diesel получаются из 4 ведер легкого топлива или 8 дизельного топлива (5/6 легкого+1/6 тяжелого топлива). Второй рецепт (скрины), очевидно, невыгоден и бессмысленен.
![2023-06-05_12 34 49](https://github.com/IdealIndustrial/GT5Unofficial/assets/18097458/b783eb48-9527-4211-8da5-4531390f4e3c)
![2023-06-05_12 34 51](https://github.com/IdealIndustrial/GT5Unofficial/assets/18097458/11beb2d7-c5fd-46f3-8e4e-0cc846022faa)

**Comment by Pilad** [comment]
У дизеля и лайт фуела калорийность одинаковая, 256к . Потому и странно,что нужно потратить больше дизельного топлива при меньшем выходе ЦБ топлива.
