### ISSUE TITLE
[FR] Паяльник форестри крафтится только в плотнике.

### ISSUE THREAD

**Issue by Fodey** [IdealIndustrial/GT5Unofficial#274]
**Относится ли ваша идея к ошибке(дизбалансу)?.**
Все структурные блоки, микросхемы и лампы форестри были перенесены в ассемблер грега, а паяльник остался в плотнике. Получается, что нужно крафтить отдельный механизм, чтобы получить возможность менять конфигурацию мультифермы.

**Опишите вашу идея**
Если перенесли все форестривское в ассемблер грега, то и паяльник желательно бы тоже перенести. Пытался добавить рецепт через скрипт майнтвикера, но он упорно не хочет добавляться.

**Comment by WiseProjects** [comment]
@SapientMC @Fodey рецепт должен быть 1в1 как в оригинале только в ассемблере? какой тир ассемблера?

**Comment by SapientMC** [comment]
@WiseProjects Рецепт такой же какой есть. Время пусть будет 5 сек и потребление 32 eU/t

**Comment by WiseProjects** [comment]
![image](https://github.com/IdealIndustrial/GT5Unofficial/assets/58177535/262eaede-00fb-4009-858a-9a287aab44c1)
