### ISSUE TITLE
[BUG]Нет сохранения инвентаря машины при перезаходе в одиночной игре.

### ISSUE THREAD

**Issue by Pilad** [IdealIndustrial/GT5Unofficial#281]
**Описание**
В одиночке сохранение инвентаря машин и возможно аутпут и инпут басов/хэтчей или пропадает или дюпается при перезаходе в игру.

**Воспроизведение**
Берем дробитель, помещаем батарейку и стак руды. Дробим хотя бы 1 блок руды. Выходим из игры и в масераторе ничего нет, пропадает батарейка и руда вся.

**Ожидаемое поведение**
Должно сохранять инвентарь машины.

**Дополнительная информация**
Скриншоты/Логи/Краши/Видеоролики относящиеся к багу

**Среда**
опишите среду в которой произошла ошибка
 - Одиночная игра.
 - 1.18.0
 - Java 8

**Comment by Pilad** [comment]
На гтнх фикс : https://github.com/GTNewHorizons/GT5-Unofficial/commit/2ed0d164315810c0c03e92d30e52225a8228ac99

**Comment by Pilad** [comment]
Работает , но проблема появляется при работе с машинами.
Берем ассемблер на 128.
Закидываем пыльки галлия и тонкую платиновую проволочку стак. И болты никель-цинк-феррита стак. Заливаем 4 слитка полиэтилена. После начала работы меха по изготовлению смд диодов закидываем 20 тонких отоженных проволочек из меди. 
Ассемблер заканчивает работу по изготовлению диодов как только кончится жидкий полиэтилен, после начинает делать катушки из феррита и проволочки. 
делает 2 операции и останется 4 отожженых медных проволочки.
Опять заливаем полиэтилен на одну операцию, 288л/2слитка.
Появляется конфликт рецептов. Ассемблер может сделать как смд диоды , так и обычные диоды из галлия и 4 отожженых медных проволочек. Но не делает не первое не второе. И продолжает стоять и думать.
Чтоб отвис нужно дать 4 медных проволочки, начнет делать катушки и вернется после к смд диодам.
![изображение](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/76b18a3d-c163-4a21-8b54-ce4245fbf058)
![изображение](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/b5dcea2d-e925-4e1a-8d9b-e7d0b03bfe3b)
![изображение](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/5d716273-2c5b-42a2-8304-c98f99a1dfa4)

**Comment by Pilad** [comment]
Можно запустить операцию если феррит болты забрать и вернуть. Если в процессе опять подлить полиэтилен мех продолжит делать смд диоды. Но если встал мех и подлить полиэтилен, то мех продолжит висеть.

**Comment by Pilad** [comment]
Хотя сразу можно поместить два конфликтующих рецепта ,залить два слитка полиэтилена и машина зависнет.
![изображение](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/e844d25e-e8e8-47bf-ae28-bb645d8e01d6)

**Comment by Pilad** [comment]
Не баг с гтнх, это и на иис такое зависание вызывается.Кидаем предметы и после полиэтилен подаём через экстрактор и мех будет висеть. 
![изображение](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/a52f564c-1c11-477d-bb82-546b380b3c37)

**Comment by Pilad** [comment]
Еще пример, если залить охлажденую лаву в центрифугу с объёмом меньше чем по рецепту и после положить например грязную пыль назеррака, то центрифуга зависает и продолжает ждать лаву, а не обрабатывать пыль.
Не знаю, правильно ли такое поведение у машин или нет.
![изображение](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/91b6623b-2242-4fd9-a1e7-ce25d728449e)

**Comment by Pilad** [comment]
Проверил на гтнх, там центрифуга берет и выполняет рецепт который возможен и не циклится на невозможном.

**Comment by SapientMC** [comment]
Это - скорее всего элемент оптимизации. Чтобы не выполнять сканирования карты рецептов после каждой операции. Пока какие-то компоненты предыдущего рецепта есть - ждем появления недостающих. А когда ничего нет - сканируем всю карту и смотрим под какой рецепт подходит то, что лежит.

**Comment by DinCraft** [comment]
Можно отлавливать события изменения инвентаря механизмов. При добавлении\удалении компонентов нужно подобрать подходящий рецепт и создать переменную, которая будет показывать кол-во раз, когда рецепт сможет быть выполнен от момента изменения состояния инвентаря. То есть, если залить охл. лаву в центрифугу, а после положить 64 латекса, майнкрафт сделает проверку рецептов 2 раза, при этом во второй раз в механизме обнаружатся компоненты для ещё одного рецепта, появится переменная: recipesLeft = componentAmount/componentAmountForRecipe (64=64/1, т.к. для рецепта центрифугирования латекса уходит ровно 1ед. латекса). И после каждого выполнения рецепта, в случае, если новых компонентов не было добавлено, нужно будет лишь уменьшать значение счётчика: recipesLeft = recipesLeft-1.

**Comment by WiseProjects** [comment]
duplicate #267
