### ISSUE TITLE
[BUG] ускорение доменной печи на 5% при увеличении heat min capacity не работает

### ISSUE THREAD

**Issue by iliapisaniy** [IdealIndustrial/GT5Unofficial#283]
**Описание**
В тултипе электронной доменной печи в nei сказано, что каждый 900 кельвинов свыше минимально температуры увеличивает скорость работы на 5% мультипликативно. При увеличении тира колец на 1 (что соответсвуте увеличению на 900 кельвинов) скорость работы не изменилась 

**Ожидаемое поведение**
Ускорение работы electric blast furnace

**Дополнительная информация**
<img width="829" alt="image" src="https://github.com/IdealIndustrial/GT5Unofficial/assets/22053655/9c532718-4f8d-4d3d-9dea-d3fdb7076130">

**Среда**
опишите среду в которой произошла ошибка
 - Одиночная игра
 - Версия ИИС 1.18.0 (включен aroma backup поставляемый со сборкой)
 - Java is version 1.8.0_381, using 64 (amd64) architecture, from Oracle Corporation

**Comment by Pilad** [comment]
Там описание не верное.Снижение потребления на 5 процентов.
![изображение](https://github.com/IdealIndustrial/GT5Unofficial/assets/9840821/036ce959-67d9-4837-b31a-40de4e6ee40c)
Смотрите гайд от Сапиента, он подробно расписал принцип разгона EBF
https://youtu.be/otsa9BiZtEc?list=PLkCDxo2DPJcP13gZjlb7GYl63eUbKBmtE

**Comment by iliapisaniy** [comment]
Ок, я понял, спасибо. Я не разбираюсь в модах на майнкрафт, но хотелось бы исправить тултип. Мы можем это сделать как-то?
