### ISSUE TITLE
[BUG] Описание LBB не соответствует действительности

### ISSUE THREAD

**Issue by arsenez2006** [IdealIndustrial/GT5Unofficial#286]
**Описание**
В описании Large Bronze Boiler указано, что за 1 единицу угля будет произведено 32000L пара со скоротью 16000L/S, время нагрева - 31.25 секунд.
Я провел некоторые эксперементы и выяснил:
1) каждый второй и последующий угольный блок вырабатывает 160000L пара (вместо 320000L)
2) первый угольный блок сгорает за 20 секунд (вне зависимости от конфигурации) и успевает выработать небольшое количество пара
3) для каждого второго и последующего угольного блока ожидаемую скорость выработки пара можно делить на 2 (конфиг - 15, скорость 500L/S вместо 1000L/s; конфиг - 8, скорость 4000L/S вместо 8000L/S)
4) используя полученные данные было вычислено время нагрева - 6.35+-0.10 секунд, с относительной погрешностью 1,57%

**Воспроизведение**
Зайти в игру, собрать тестовую установку и, используя ручку, лист бумаги, секундомер и калькулятор, посчитать.

**Ожидаемое поведение**
Играть в игру хотя бы без секундомера.

~~**Дополнительная информация**~~

**Среда**

- Одиночный мир
- ИИС 1.18

**Comment by Pilad** [comment]
Бронзовый бойлер вырабатывает 16000 пара. Читайте внимательно тултип.

**Comment by arsenez2006** [comment]
> Бронзовый бойлер вырабатывает 16000 пара. Читайте внимательно тултип.

Produces 32000.0L of Steam with 1 Coal at 16000L/S
В чём я не прав?

**Comment by Pilad** [comment]
> > Бронзовый бойлер вырабатывает 16000 пара. Читайте внимательно тултип.
> 
> Produces 32000.0L of Steam with 1 Coal at 16000L/S В чём я не прав?

1. Бойлер вырабатывает 16000 л/с , 32к пара за один уголь. 800 л/т если угодно.
2. Бойлер при нагреве игнорирует микросхему и время горения в этот момент одно, после достижения 100 процентов и при наличии/отстутствии микросхемы время уже будет иное.

**Comment by arsenez2006** [comment]
> Бойлер вырабатывает 16000 л/с , 32к пара за один уголь. 800 л/т если угодно.
В этом то и проблема, я отдельно запускал бойлер на одном угольном блоке и на двух, посчитал сколько выработал второй угольный блок и получил 160000, а не 320000.

Скорость без конфига я не мерил, но, как и написал выше, получил скорость в 2 раза меньше заявленной.

> Бойлер при нагреве игнорирует микросхему и время горения в этот момент одно, после достижения 100 процентов и при наличии/отстутствии микросхемы время уже будет иное.

При первом запуске бойлера я клал в него 1 угольный блок, который полностью отрабатывал за 20 секунд, при этом успевал выработать немного пара. Каким бы аутистом я не был, просрать 10 секунд на секундомере нереально.

**Comment by Pilad** [comment]
> > Бойлер вырабатывает 16000 л/с , 32к пара за один уголь. 800 л/т если угодно.
> > В этом то и проблема, я отдельно запускал бойлер на одном угольном блоке и на двух, посчитал сколько выработал второй угольный блок и получил 160000, а не 320000.
> 
> Скорость без конфига я не мерил, но, как и написал выше, получил скорость в 2 раза меньше заявленной.
> 
> > Бойлер при нагреве игнорирует микросхему и время горения в этот момент одно, после достижения 100 процентов и при наличии/отстутствии микросхемы время уже будет иное.
> 
> При первом запуске бойлера я клал в него 1 угольный блок, который полностью отрабатывал за 20 секунд, при этом успевал выработать немного пара. Каким бы аутистом я не был, просрать 10 секунд на секундомере нереально.

Видео, 32 секунды нагрев. https://drive.google.com/file/d/1dLMnTVvW54ZoNrBN-3f9E8TNYo8lM89H/view?usp=sharing

**Comment by Pilad** [comment]
Вычисляем номинальную выработку 800 л/т или 16к/с
https://drive.google.com/file/d/1mBPlGJHt5La7k_LquoNqWAZHvXBPcumn/view?usp=sharing

**Comment by Pilad** [comment]
Выход с микросхемой 8 и 10
https://drive.google.com/file/d/1Hq-XY6jAxMVMjL5_4DGwGVlqUIYA766C/view?usp=sharing

**Comment by arsenez2006** [comment]
Разобрался. Не знал, что эффективность снижается, если не исправить все проблемы в maintenance hatch. Спасибо за помощь.
